---
title: "voting-rights-v2"
author: "margaret"
date: "3/30/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r library, message=F}
library(tidyverse)
library(janitor)
library(scales)
```

data from: https://dl.ncsbe.gov/index.html?prefix=data/Snapshots/

```{r load-data}
durham21 <- read_csv("data/duke_2021.csv")
durhamhist <- read_tsv("data/ncvhis32.txt")
```


```{r find-students}
duke_students <- durham21 %>%
  filter(
    street_name %in% c("DUKE UNIVERSITY WEST CAMPUS", 
                       "DUKE UNIVERSITY EAST CAMPUS", "TOWERVIEW", "ALEXANDER", 
                       "YEARBY") |
      (street_name %in% c("BASSETT", "EPWORTH", "FEW QUAD", "GILBERT ADDOMS", 
                          "GILES", "JARVIS", "MAXWELL", "MIRECOURT", "PEGRAM", 
                          "RANDOLPH", "RANDOLPH HALL", "ROUND TABLE", 
                          "SOUTHGATE", "WAYNE MANOR", "WILSON", "WANNAMAKER") && 
         street_type_cd == "DORM") |
      (street_name == "SWIFT" & house_num == "300") |
      (street_name == "CAMPUS"  & str_detect(house_num, "13\\d\\d"))
  )
```


```{r}
full_data <- left_join(
  duke_students, 
  durhamhist, 
  by = c("voter_reg_num" = "voter_reg_num")
  ) %>%
  mutate(
    registr_yr = lubridate::year(registr_dt),
    datev = as.Date(election_lbl, format = "%m/%d/%Y"),
    voted_year = lubridate::year(datev)
    ) %>%
  filter(!is.na(election_lbl))

election_year <- full_data %>%
  filter(
    str_detect(election_desc, "GENERAL"),
    voted_year %in% c(2004, 2008, 2012, 2016, 2020)
    ) %>%
  select(voter_reg_num, voted_year) %>%
  distinct() %>%
  count(voted_year)
  

election_yr_reg <- duke_students %>%
  mutate(cancel_yr = lubridate::year(cancellation_dt)) %>%
  mutate(
    cancel_yr = ifelse(cancel_yr == 1900, 2023, cancel_yr)
  ) %>%
  transmute(voter_reg_num, year = map2(registr_yr, cancel_yr, seq, by = 1)) %>%
  unnest(cols = c(year)) %>%
  filter(year %in% c(2004, 2008, 2012, 2016, 2020)) %>%
  select(voter_reg_num, year) %>%
  distinct() %>%
  count(year)

newly_reg <- duke_students %>%
  filter(registr_yr %in% c(2004, 2008, 2012, 2016, 2020)) %>%
  select(voter_reg_num, registr_yr) %>%
  distinct() %>%
  count(registr_yr)
```

```{r}
prop_table <- election_year %>% 
  rename(year = voted_year, num_voted  = n) %>%
  full_join(
    election_yr_reg %>%
      rename(num_registered = n)
  ) %>%
  full_join(
    newly_reg %>%
      rename(year = registr_yr, num_actively_registered = n)
  ) %>%
  mutate(
    active_prop = num_actively_registered / num_registered,
    voted_prop = num_voted / num_registered
  )
```


```{r}
duke_students %>%
  mutate(registr_yr = lubridate::year(registr_dt)) %>%
  count(registr_yr) %>%
  filter(registr_yr >= 2000) %>%
  ggplot(aes(x = registr_yr, y = n)) +
  geom_line() +
  geom_line(data = newly_reg, color = "red") +
  geom_point(data = newly_reg, color = "red", size = 3) +
  scale_y_continuous(labels = scales::label_comma()) +
  scale_x_continuous(breaks = seq(2000, 2020, by = 4)) +
  labs(
    x = "Year",
    y = "Number of Duke students actively registered"
  ) +
  theme_minimal()
```

```{r}
durham21 %>%
  count(street_name, street_type_cd) %>%
  arrange(desc(n))

durham21 %>%
  count(ncid) %>%
  arrange(desc(n))
```


```{r}
duke_students %>%
  count(registr_yr, party_desc) %>%
  filter(registr_yr >= 2000,
         registr_yr %% 4 == 0) %>%
  ggplot(aes(x = registr_yr, y = n, color = party_desc)) +
  geom_line() +
  geom_point() +
  scale_y_continuous(labels = scales::label_comma()) +
  scale_x_continuous(breaks = seq(2000, 2020, by = 4)) +
  scale_color_manual(values = c("blue4", "green3", "red3", "grey")) +
  labs(
    x = "Year",
    y = "Number of Duke students registered"
  ) +
  theme_minimal()
```


```{r}
duke_students %>%
  filter(registr_yr >= 2000, registr_yr %% 4 == 0) %>%
  ggplot(aes(x = registr_yr, fill = fct_rev(fct_infreq(party_desc)))) +
  geom_bar(position = "fill") +
  scale_x_continuous(breaks = seq(2000, 2020, by = 4)) +
  scale_fill_manual(values = c("green3", "red3", "blue4", "grey")) +
  labs(
    x = "Year",
    y = NULL,
    fill = "Party",
    title = "Duke students' registered party over time"
  ) +
  theme_minimal()
```



```{r}
full_data %>%
  distinct(voter_reg_num, .keep_all = T) %>%
  count(voted_year) %>%
  ggplot(aes(x = voted_year, y = n)) +
  geom_line() +
  geom_line(data = election_year, color = "red") +
  geom_point(data = election_year, color = "red", size = 3) +
  scale_y_continuous(labels = scales::label_comma()) +
  scale_x_continuous(breaks = seq(2000, 2020, by = 4)) +
  labs(
    x = "Year",
    y = "Number of Duke students who voted"
  ) +
  theme_minimal()
```


```{r}
ggplot() +
  geom_line(data = election_yr_reg, aes(x = year, y = n, color = "Registered")) +
  geom_line(data = election_year, aes(x = voted_year, y = n, color = "Voted")) +
  geom_line(data = newly_reg, aes(x = registr_yr, y = n, color = "Active Registration")) +
  geom_point(data = election_yr_reg, aes(x = year, y = n, color = "Registered")) +
  geom_point(data = election_year, aes(x = voted_year, y = n, color = "Voted")) +
  geom_point(data = newly_reg, aes(x = registr_yr, y = n, color = "Active Registration")) +
  scale_y_continuous(labels = scales::label_comma()) +
  scale_x_continuous(breaks = seq(2012, 2020, by = 4), limits = c(2012, 2020)) +
  scale_color_manual(
    name = "Duke Students",
    breaks = c("Voted", "Registered", "Active Registration"),
    values = c("Voted" = "blue", "Registered" = "red", 
               "Active Registration" = "green")
  ) +
  labs(
    x = "Year",
    y = "Number of Duke students",
    title = "Number of Duke students who voted vs who registered to vote"
  ) +
  theme_minimal()
```


```{r}
full_data %>%
  filter(voted_year %in% seq(2012, 2020, 4)) %>%
  ggplot(
    aes(x = voted_year, fill = fct_rev(fct_infreq(voting_method)))
  ) +
  geom_bar(position = "fill") +
  colorblindr::scale_fill_OkabeIto() +
  labs(
    x = "Year", 
    y = NULL,
    fill = "Voting method",
    title = "Duke students' voting method over time"
  ) +
  theme_minimal()
```

```{r}
full_data %>%
  filter(voted_year %in% seq(2012, 2020, 4)) %>%
  ggplot(
    aes(x = voted_year, fill = fct_rev(fct_infreq(voted_party_desc)))
  ) +
  geom_bar(position = "fill") +
  scale_fill_manual(values = c("green3", "red3", "grey", "blue4")) +
  labs(
    x = "Year", 
    y = NULL,
    fill = "Party",
    title = "Duke students' voted party over time"
  ) +
  theme_minimal()
```

